name: Ruff

on:
  push:
    paths:
      - "mdmodels/**"
      - "tests/**"
      - "pyproject.toml"
  pull_request:
    paths:
      - "mdmodels/**"
      - "tests/**"
      - "pyproject.toml"

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v2
        with:
          src: >-
            mdmodels/
            tests/
